version: '3.3'

services:
  star-product-database:
    container_name: star-product-database
    hostname: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    env_file:
      - ../.env
    networks:
      - star-product
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server --requirepass admin --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/duducp/Redis:/var/lib/postgresql/data
    networks:
      - star-product
  star-product-api-app:
    container_name: star-product-api-app
    restart: always
    image: star-product
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run dev
    ports:
      - "3333:3333"
      - "9229:9229"
    env_file:
      - ../.env
    networks:
      - star-product
    extra_hosts:
      - external:192.168.1.1
volumes:
  database:

networks:
  star-product:
    driver: bridge